# Generated by Django 4.1 on 2023-05-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContradictedDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredienta", models.CharField(max_length=255)),
                ("ingredient_codea", models.CharField(max_length=50)),
                ("product_namea", models.CharField(max_length=255)),
                ("companya", models.CharField(max_length=255)),
                (
                    "ingredientb",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ingredient_codeb",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "product_nameb",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("companyb", models.CharField(blank=True, max_length=255, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "contraindicated_drug",},
        ),
    ]
