# Generated by Django 4.1 on 2023-05-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0002_contradicteddrug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContradictedDrug", new_name="ContraindicatedDrug",
        ),
    ]
