# Generated by Django 4.1 on 2023-05-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0003_rename_contradicteddrug_contraindicateddrug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contraindicateddrug", old_name="companya", new_name="company_a",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug", old_name="companyb", new_name="company_b",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="ingredienta",
            new_name="ingredient_a",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="ingredientb",
            new_name="ingredient_b",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="ingredient_codea",
            new_name="ingredient_code_a",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="ingredient_codeb",
            new_name="ingredient_code_b",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="product_namea",
            new_name="product_name_a",
        ),
        migrations.RenameField(
            model_name="contraindicateddrug",
            old_name="product_nameb",
            new_name="product_name_b",
        ),
    ]
